default:
  KAFKA_BROKER_URL: kafka://localhost:9092
  WEBSITES: {
    "https://google.com": ["Feeling Lucky", "something"],
    "https://example.org": ["Example Domain"]
  }
  DATABASE:
      dbname: websitecheck
      user: postgres
      password: secret
      host: 0.0.0.0
      port: 5432

staging:
  KAFKA_BROKER_URL: kafka://kafka1
  USE_SASL: True

testing:
  DATABASE:
      dbname: testdb
      user: postgres
      password: secret
      host: 0.0.0.0
      port: 16766
  WEBSITES: {
    "http://test1_url": ["test123", "test789"],
    "http://test2_url": ["test123"],
    "http://test3_url": [],
  }

  KAFKA_BROKER_URL: kafka://kafka
