default:
  kafka_broker_url: kafka://localhost:9092
  use_sasl: false
  websites: {
    "https://google.com": ["feeling lucky", "something"],
    "https://example.org": ["example domain"]
  }
  producer_frequency: 1
  database:
      dbname: websitecheck
      user: postgres
      password: secret
      host: 0.0.0.0
      port: 5432
  default_db: null

staging:
  kafka_broker_url: kafka://kafka1
  use_sasl: true

testing:
  database:
      dbname: testdb
      user: postgres
      password: secret
      host: 0.0.0.0
      port: 16766
  websites: {
    "http://test1_url": ["test123", "test789"],
    "http://test2_url": ["test123"],
    "http://test3_url": [],
  }

  kafka_broker_url: kafka://kafka
